---
vps:
  # Список полезных пакетов, которыми часто пользуются
  packages:
    - nano
    - mc
    - tree
    - net-tools
    - htop
    - ncdu
    - ufw
    - fail2ban

  # Отключение IPv6
  ipv6-disable: true # Запускает скрипт switch-ipv6.sh

  # Список приложений на сервере
  applications:
    # Изменение порта для сервера ssh
    ssh:
      port: 60022
    fail2ban:
    ufw:
    docker:
    openvpn:
      port: 61194
    outline:
      port:
        api: 61195
        keys: 61196

  # Пользователи, которыее должны быть  
  users:
    # Пользователь, для управления контейнерами Docker
    - name: "docker"
      pass: "!@#QWE123qwe" # Напиши сюда свой пароль !
      home-dir: true
      allow_ssh: false # возможность подключения по SSH
      sudoer: false
    # Пользователь для сервисных работ и настройки VPS
    - name: "ssh"
      pass: "!@#QWE123qwe" # Напиши сюда свой пароль !
      home-dir: false
      allow_ssh: true
      sudoer: true

# Настройки клиента запуска (локальная машина)
client:
  # Таймаут SSH-подключения в секундах (ConnectTimeout)
  ssh-connect-timeout: 2
  # Количество попыток переподключения по SSH
  ssh-reconnect-attempts: 5